package com.mygdx.game.UI;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.g2d.BitmapFont;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.ui.Label;
import com.badlogic.gdx.utils.viewport.FitViewport;
import com.mygdx.game.Character.Mouse;
import com.mygdx.game.Restrictions;

public class GUI implements Restrictions {
    private Stage stage;
    private Label label;
    private Mouse mouse;
    private BitmapFont font = new BitmapFont();
    private FitViewport fitViewport;

    public GUI(Mouse mouse, FitViewport fitViewport) {
        this.mouse = mouse;
        this.fitViewport = fitViewport;

        stage = new Stage(fitViewport);
        Gdx.input.setInputProcessor(stage);
        label = new Label("Hello",new Label.LabelStyle(font,new Color(Color.WHITE)));
        stage.addActor(label);
    }

    public void render(SpriteBatch batch){
        stage.act();
        stage.draw();
        //font.draw(batch, "x: "+ mouse.getTileX(cam) + "y: " + mouse.getTileY(cam),-10, 0);
    }

    public void dispose(){
        font.dispose();
    }
}
